[usuario."jose.gomes"]
nome = "José Gomes"
email = "jose.filho@mv.com.br"
senha_hash = "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
tipo = "a"
requer_reset = "nao"

[usuario."pedro.mendes"]
nome = "Pedro Mendes"
email = "pedromendesfilho@gmail.com"
senha_hash = "3d9cf8bbda12670cba72c47d1271127c549e41fd998116240978d5bc66dbb90d"
tipo = "g"
requer_reset = "nao"

[usuario."pedro.bessa"]
nome = "Pedro Reagnait"
email = "pedro.bessa@aquila.com.br"
senha_hash = "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
tipo = "g"
requer_reset = "nao"

[usuario."evandro.macedo"]
nome = "Evandro Macedo Santana"
email = "evandromsantana@hotmail.com"
tipo = "g"
senha_hash = "e115d2e8691f9dcb0e7a5b29a71ff442b51f89439dc5d324a03f7403eac1d67e"
requer_reset = "sim"

[usuario.valdiano]
nome = "Valdiano Sousa"
email = "evandromsantana@hotmail.com"
tipo = "c"
senha_hash = "52e8e47b38e854580afce4aade15dbd5ce0c0464da711afe71da123687d5a4cd"
requer_reset = "nao"

